### PR TITLE
Add dynamic filters to people list

### PR DESCRIPTION
**Pull request by minsukkahng**
Hi, I've created dynamic filters for the people page. Thank you.

### CODE REVIEW

**Comment by e9t** [comment]
What a wonderful feature!
I have two suggestions before we merge this pull request.

1. At initial load, shouldn't the checkboxes all be checked?
2. How about adding a "Toggle all" button?

Additionally, I think we can speed up the page loading if we could serve person images directly from the popong server instead of requesting from assembly.go.kr, because that way we can serve smaller, resized images, for the people lists. (And perhaps we can request images to assembly.go.kr every week or so for updates, too. This can be created as a separate issue.)

Please tell me what you think, and thanks for the pull request :)

**Comment by minsukkahng** [comment]
Thanks for your suggestions. :-)

As for the initial state of checkboxes, I don't think they should be checked by default. The current approach is more natural and widely used (See websites like Amazon, LinkedIn). Although it might be confusing to developers at first, users have no difficulty using it. They usually add filters one by one (e.g., I am interested in people in 30s), not remove filters (I am NOT interested in people in 30s). Technically, by default, there is no WHERE conditions, and as checkboxes are added, it can be thought clauses are added (e.g., ages='30' or ages='40'). When all checkboxes are checked, it is the same as when no checkbox is checked. Then we might not need the "toggle all" button, right?

As for storing images, I strongly like your suggestion. I've tried to figure out how to implement the feature, it seems to difficult for me to understand the internal mechanisms. I hope someone can work on this feature.

Please let me know if you have any further issues to discuss. Thanks!

**Comment by e9t** [comment]
Convinced! Let's pull this.

**Comment by e9t** [comment]
@minsukkahng, before shipping this feature, I thought we could make some interface improvements and applied the following modifications (https://github.com/teampopong/pokr.kr/commit/18fc164527e3960b4a9ceee05558341d4bdb02e7).

- Added labels to each filter
- Used bootstrap's grid system for page layout

If you agree this is an improvement to the interface, let's deploy this feature along with the interface modifications. Otherwise, lets discuss how we can tweak some details for the convenience of the users.

#### Web
Before and after


#### Mobile
Before and after

**Comment by minsukkahng** [comment]
This is great! It would be much better. I thought you don't want to use sidebars.

**Comment by e9t** [comment]
Great! :+1:

**Pull request merged**
